name: peddler
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  fluttertoast: ^8.0.7
  firebase_storage: 11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/inicio.png
    - assets/usuario.png
    - assets/back.png
