// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOxhaMSuK7Ees3n4A5o4hdDIyT6LdD7go',
    appId: '1:485782064549:web:33596cac70ddf997c16c4c',
    messagingSenderId: '485782064549',
    projectId: 'peddler-ingsoft2023',
    authDomain: 'peddler-ingsoft2023.firebaseapp.com',
    storageBucket: 'peddler-ingsoft2023.appspot.com',
    measurementId: 'G-SXYP3VRME7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApDPjyjgVdPRyeNfcr0Yi13TTvTeydwjw',
    appId: '1:485782064549:android:1f8853a99c7f56bec16c4c',
    messagingSenderId: '485782064549',
    projectId: 'peddler-ingsoft2023',
    storageBucket: 'peddler-ingsoft2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGkdk_jj05hLG164xAa85k24nPLawcWKo',
    appId: '1:485782064549:ios:ffde4c9570409f8dc16c4c',
    messagingSenderId: '485782064549',
    projectId: 'peddler-ingsoft2023',
    storageBucket: 'peddler-ingsoft2023.appspot.com',
    iosBundleId: 'com.example.peddler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGkdk_jj05hLG164xAa85k24nPLawcWKo',
    appId: '1:485782064549:ios:ad0c6a06a0dd9798c16c4c',
    messagingSenderId: '485782064549',
    projectId: 'peddler-ingsoft2023',
    storageBucket: 'peddler-ingsoft2023.appspot.com',
    iosBundleId: 'com.example.peddler.RunnerTests',
  );
}
